### ISSUE TITLE
ON/OFF Climate

### ISSUE THREAD

**Issue by JeedHome44** [rbiremon/hass-comapsmarthome#2]
Hello,
It's work perfectly but !
is ti possible to add service to active/desactive climate ?
we can do it in App to do target temperature to 4 degres during summer.
Thank you

**Comment by JeedHome44** [comment]
![image](https://user-images.githubusercontent.com/41892950/236564979-e6d95fdd-6fab-4c5e-bafd-04e9a1705930.jpeg)

Hello,
My request concerns the red button
Thank you

**Comment by rbiremon** [comment]
There is now a switch available on the main device to toggle heating on/off: https://github.com/rbiremon/hass-comapsmarthome/releases/tag/v1.1.0
