### ISSUE TITLE
Problème de remonté d'états

### ISSUE THREAD

**Issue by MBA78** [rbiremon/hass-comapsmarthome#4]
Bonjour,
Avant tout merci pour cette intégration. Je rencontre toutefois des problèmes.
J’utilise un comap/qivivo avec plusieurs zones : une gérée par thermostat et les autres par fil pilote.
Il semble y avoir un problème avec la remonté des états.
Pour la zone gérée par le fil pilote, elle affiche bien les différents états tels que 'confort,' 'eco', etc. Je peux changer de mode, mais le retour d’état sur HA revient toujours sur 'Absent'. La commande est bien reçu sur le comap.
Par exemple, si l’application comap montre le mode « hors gel » et que je sélectionne « confort » sur la carte HA, l’application comap change pour « confort », mais la carte ne se met pas à jour en conséquence et reste sur «Absent». De même, un changement effectué directement sur l’application comap ne met pas à jour la carte. On dirait que l’intégration ne récupère pas l’état actuel.
Le problème est le même avec la zone gérée par le thermostat.

**Comment by rbiremon** [comment]
C'est corrigé, je pense que ça n'a jamais marché avant.

Si tu changes via home assistant, les remontées devraient être immédiates.
En revanche pour un changement depuis l'application comap, cela peut prendre 30s (polling à intervalle fixe)
