### ISSUE TITLE
Pas de remontée de la consigne dans HA

### ISSUE THREAD

**Issue by aldoushx** [rbiremon/hass-comapsmarthome#5]
Bonjour,
La nouvelle MaJ (ou la précédente ?) ne fait plus remonter la température de consigne dans l'entité climate. La consigne est égale a la température courante.

**Comment by rbiremon** [comment]
Je pense que cela est résolu par la dernière release https://github.com/rbiremon/hass-comapsmarthome/releases/tag/v1.1.1 ?
En tout cas de mon côté j'ai bien une rémontée de la consigne et la temperature courante 

![image](https://github.com/rbiremon/hass-comapsmarthome/assets/6417617/5f025fc9-9fc6-49d1-aa09-aeb6059c590b)

**Comment by aldoushx** [comment]
J'ai installé la dernière release, et effectivement tout est OK !
Super travail au passage sur l’intégration.
